### ISSUE TITLE
Crates System (Priority Low)

### ISSUE THREAD

**Issue by KenzyHere7** [TiagoFar78/BlockBattles#21]
```
Box List:
- Box
  Wooden (6 ore) 60%
  Silver (12 ore) 35%
  Amethyst (24 ore) 5%
Vip Crates:
  Large (Price: 500 Cloux)
  Golden (Price: 950 Cloux)
  Mythic (Price: 4750 Cloux)
```
ANY CRATE can unlock blocks of any rank that is current or lower.
After ranking down, blocks from higher ranks that were previously unlocked will not be lost.
>Example: If you are rank Iron, it is not possible to unlock Netherite blocks in crates.
> This assures players that if they are demoted to a lower rank, they will still retain access to any blocks they had unlocked when they were at a higher rank.

### After win a game
- After winning a match, regardless of the mode (unrated, etc.), you receive a Box.
80% Wooden Box
17% Silver Box
3% Amethyst Crate

- If you win with a special condition, for example, if you win with 1 HP remaining, the probabilities change:
60% Wooden Box
20% Silver Box
15% Amethyst Crate
3% Large Crate
2% Golden Crate

### How to Open Boxes/Crates:
**In the lobby, there is a dedicated area for crates.**
To the left of this area, there is a "machine" that, when interacted with, opens a GUI.
In this GUI, you can insert up to 3 crates. (VIP members will have one additional slot.)
Once a crate is placed in an empty slot, it will start to open.

```
Box/Crate Opening Times:
- Wooden Box: 2 hours
- Silver Box: 4 hours
- Amethyst Crate: 10 hours
- Large Crate: 12 hours
- Golden Crate: 16 hours
- Mythic Crate: 24 hours
```

### ToDo:
Animation for opening the crates

**Comment by TiagoFar78** [comment]
This is not in the scope of the plugin. BlockBattles plugin should focus only on the game itselft. If you want this system on your server you have to find an already existing crates plugin (there are a bunch online).

For the integration of this plugin with a crates plugin I will have in the config an area for rewards, where you can put commands to be executed when the game ends. And for the part where blocks will be unlocked, it should also work based on commands. When a player finds a block a command is executed and that will be taken care of in this plugin.

You can either edit and reopen this issue or create a new one to specify the commands.
