### ISSUE TITLE
/Spawn bug

### ISSUE THREAD

**Issue by KenzyHere7** [TiagoFar78/BlockBattles#30]
I added `EssentialsSpawn plugin` on the server, so people will be able to leave when they are stuck in a game, but if they do it during a game, they enter the lobby with the match items.
it's not a very serious bug, because as soon as they start another game, other blocks arrive.
maybe you could make it so that if they leave BlockBattleWorld, it automatically counts as a lost game

**Comment by TiagoFar78** [comment]
It doesn't happen to me. Can you replicate this bug?

**Comment by KenzyHere7** [comment]
> It doesn't happen to me. Can you replicate this bug?

![image](https://github.com/user-attachments/assets/da0f4279-05bb-4b55-ac92-b09b54a86c5f)

**Comment by TiagoFar78** [comment]
That only happens because of the plugins you have installed. And because you allow players to execute commands in the world. I don't think that this plugin should cover this bug.
